version: "3.1"
services:

    mysql:
      image: mysql:5.7
      container_name: turnos-desligar-me-mysql
      working_dir: /application
      volumes:
        - ./dump.sql:/application/dump.sql
      command: bash -c "cd application && cat dump.sql | mysql -h mysql -uturnos -pturnos turnos"
      environment:
        - MYSQL_ROOT_PASSWORD=turnos
        - MYSQL_DATABASE=turnos
        - MYSQL_USER=turnos
        - MYSQL_PASSWORD=turnos
      ports:
        - "8101:3306"

    webserver:
      image: nginx:alpine
      container_name: turnos-desligar-me-webserver
      working_dir: /application
      volumes:
          - .:/application
          - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "8001:80"
      links:
       - mysql
       - php-fpm

    php-fpm:
      build: 
        dockerfile: phpdocker/php-fpm/Dockerfile
        context: ./
      container_name: turnos-desligar-me-php-fpm
      working_dir: /application
      volumes:
        - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.2/fpm/conf.d/99-overrides.ini
      links:
        - mysql
